server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candyquizz
    username: postgres
    password: MYdatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yanissvaljean@gmail.com
    password: dliorftodimzawuj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
